In [23]:
from datetime import timedelta
from string import ascii_letters, digits
from os import mkdir, path
import nest_asyncio
import pandas as pd
import twint

nest_asyncio.apply()

def clean_name(dirname):
    
    valid = set(ascii_letters + digits)
    return ''.join(a for a in dirname if a in valid)


def twint_search(searchterm, since, until, json_name):

    c = twint.Config()
    c.Search = searchterm
    c.Since = since
    c.Until = until
    c.Limit = 100
    c.Lang = "id"
    c.Hide_output = True
    c.Store_json = True
    c.Output = json_name
    c.Debug = True

    try:
        twint.run.Search(c)    
        
    except (KeyboardInterrupt, SystemExit):
        raise
        
#     except:
#         print("Problem with %s." % since)


def twint_loop(searchterm, since, until):

    dirname = clean_name(searchterm)
    
    try:
        mkdir(dirname)
        print("Directory" , dirname ,  "Created ")
        
    except FileExistsError:
        print("Directory" , dirname ,  "already exists")

    daterange = pd.date_range(since, until)

    for start_date in daterange:

        since= start_date.strftime("%Y-%m-%d")
        until = (start_date + timedelta(days=1)).strftime("%Y-%m-%d")

        json_name = '%s.json' % since
        json_name = path.join(dirname, json_name)

        print('Getting %s ' % since )
        twint_search(searchterm, since, until, json_name)

In [24]:
twint_loop('corona OR covid19', '01-01-2020', '01-31-2020')

Directory coronaORcovid19 already exists
Getting 2020-01-01
Getting 2020-01-02
Getting 2020-01-03
Getting 2020-01-04
Getting 2020-01-05
Getting 2020-01-06
Getting 2020-01-07
Getting 2020-01-08
Getting 2020-01-09
Getting 2020-01-10
Getting 2020-01-11
Getting 2020-01-12
Getting 2020-01-13
Getting 2020-01-14
Getting 2020-01-15
Getting 2020-01-16
Getting 2020-01-17
Getting 2020-01-18
Getting 2020-01-19
Getting 2020-01-20
Getting 2020-01-21
Getting 2020-01-22
Getting 2020-01-23
Getting 2020-01-24
Getting 2020-01-25
Getting 2020-01-26
Getting 2020-01-27
Getting 2020-01-28
Getting 2020-01-29
Getting 2020-01-30
Getting 2020-01-31

In [25]:
from glob import glob

file_names = glob(path.join('coronaORcovid19','*.json'))
dfs = [pd.read_json(fn, lines = True) for fn in file_names]
corona = pd.concat(dfs)
corona

,id,conversation_id,created_at,date,time,timezone,user_id,username,name,place,...,geo,source,user_rt_id,user_rt,retweet_id,reply_to,retweet_date,translate,trans_src,trans_dest
0,1212402242730504193,1212402242730504192,2020-01-01 15:56:34,2020-01-01,22:56:34,SE Asia Standard Time,2929079279,tshepoboldwick,tshepo boldwick,,...,,,,,,"[{'user_id': '2929079279', 'username': 'Tshepo...",,,,
1,1212387683252621312,1212097669557915648,2020-01-01 14:58:43,2020-01-01,21:58:43,SE Asia Standard Time,1401126475,rzzzzkyy,Entah kenapa,,...,,,,,,"[{'user_id': '1401126475', 'username': 'Rzzzzk...",,,,
2,1212374434884902912,1212367796719382528,2020-01-01 14:06:04,2020-01-01,21:06:04,SE Asia Standard Time,907233965362135041,corona_kafir,Sora TaranBala,,...,,,,,,"[{'user_id': '907233965362135041', 'username':...",,,,
3,1212373836483584001,1212367796719382528,2020-01-01 14:03:42,2020-01-01,21:03:42,SE Asia Standard Time,907233965362135041,corona_kafir,Sora TaranBala,,...,,,,,,"[{'user_id': '907233965362135041', 'username':...",,,,
4,1212373592719024129,1212373592719024128,2020-01-01 14:02:43,2020-01-01,21:02:43,SE Asia Standard Time,1113770528534188033,corona_virus09,Ching chong,,...,,,,,,"[{'user_id': '1113770528534188033', 'username'...",,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55,1219616346578702337,1219616346578702336,2020-01-21 13:42:51,2020-01-21,20:42:51,SE Asia Standard Time,1497797029,bangtaxid,My Documents,,...,,,,,,"[{'user_id': '1497797029', 'username': 'Bangta...",,,,
56,1219615579901816832,1219615579901816832,2020-01-21 13:39:48,2020-01-21,20:39:48,SE Asia Standard Time,83086683,dangerrys,SkyChickenIsLaunching,,...,,,,,,"[{'user_id': '83086683', 'username': 'dangerry...",,,,
57,1219613775160119299,1219613775160119296,2020-01-21 13:32:37,2020-01-21,20:32:37,SE Asia Standard Time,1085851244680351745,watetezitv,WateteziTV,,...,,,,,,"[{'user_id': '1085851244680351745', 'username'...",,,,
58,1219612562590879747,1219612562590879744,2020-01-21 13:27:48,2020-01-21,20:27:48,SE Asia Standard Time,906747060421931009,m_agung777,Moh. Agung,,...,,,,,,"[{'user_id': '906747060421931009', 'username':...",,,,
59,1219610917832482816,1219610917832482816,2020-01-21 13:21:16,2020-01-21,20:21:16,SE Asia Standard Time,95579729,wolipop,wolipop,,...,,,,,,"[{'user_id': '95579729', 'username': 'wolipop'}]",,,,

In [26]:
corona.to_csv("coronaORcovid19/coronaORcovid19.csv", index = False)